### ISSUE TITLE
Ability to set labels and annotations.

### ISSUE THREAD

**Issue by DanTulovsky** [otterize/helm-charts#109]
Hi,

It would be super helpful to be able to set additional labels and annotations on any `Deployment` and `StatefulSet` objects that the operator installs (and on the operator itself).  Our cluster has requirements that certain labels and annotations are present and these helm charts don't allow setting them.

Thank you
Dan

**Comment by usarid** [comment]
Thanks for the suggestion Dan. We’ll take a look at it tomorrow.

**Comment by omris94** [comment]
Hey @DanTulovsky , I've just merged https://github.com/otterize/helm-charts/pull/110 . This PR allows you setting annotations and labels of resources created by installing this helm chart by setting these values:

- `global.commnonAnnotations` / `global.commonLabels` - for setting annotations/labels for every object created by this chart (including Deployment/Statefulset).
- `global.podAnnotations `/ `global.podLabels` - for setting annotations/labels for every pod created by this chart.

What do you think about it? 

Thanks ,
Omri
