### ISSUE TITLE
The CLA link is broken in the CLA bot

### ISSUE THREAD

**Issue by victor-ufg** [otterize/helm-charts#182]
**Describe the bug**:
The cla bot is pointing me to a non-existing url:
https://github.com/otterize/cla/blob/main/otterize-individual-cla-v1.0.mdx

![image](https://github.com/otterize/helm-charts/assets/105295869/e96c31d6-dfeb-403c-8ba0-9af74ee93cc8)

**Expected behaviour**:
The CLA link actually works :) I couldn't find any reference to that particular link in this repo, the cla-bot repo, nor the otterize docs. I assume it's in your internal config ;)

 Maybe a good idea would be to keep the CLA document together with the repo contributing to? (I.E. This repo)

**Steps to reproduce the bug**:
Create a PR, wait for cla-bot to post a comment.

**Comment by orishoshan** [comment]
Thank you, fixed! Correct link is here: https://github.com/otterize/cla/blob/main/otterize-individual-cla-v1.0.md
