### ISSUE TITLE
add to network-mapper sniffer-daemonset an option to set tolerations and priorityClassName in helm chart

### ISSUE THREAD

**Issue by romga** [otterize/helm-charts#92]
when I deploy network-mapper the sniffer-deamonset not starting on nodes that i have some taints on.
I want to have the option to set tolerations for this deamoset.
Also, i would like to be able to set it  priorityClassName, so i can make sure it deployed across all nodes in the system

**Comment by orishoshan** [comment]
Closed in #93. Thanks @romga!
